# This workflow builds a production-ready package when a tag is created.
#
# This workflow is based on the `5_builderpackage_base-dev-environment` workflow.

name: Build

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build app package (auto)
    uses: ./.github/workflows/5_builderpackage_base-dev-environment.yml
    with:
      reference: ${{ github.ref_name }}
      command: 'yarn build'
      artifact_name: 'wazuh-security-dashboards-plugin-${{ github.ref_name }}'
      artifact_path: './wazuh-security-plugin/build'