# This workflow is based on the `5_builderprecompiled_base-dev-environment` workflow.
#
# This workflow:
# - 🖇️ Allows manual builds or from other workflows, specifying any valid code reference (branch/tag/commit SHA).
# - 🛠️ Builds a production-ready package of the `wazuh-security-dashboards-plugin` from the given Git reference.
# - ⚡ Reuses a preconfigured build environment, simplifying maintenance.

name: Manual build

on:
  workflow_call:
    inputs:
      reference:
        required: true
        type: string
        description: Source code reference (branch, tag or commit SHA)
        default: 4.10.0
  workflow_dispatch:
    inputs:
      reference:
        required: true
        type: string
        default: main
        description: Source code reference (branch, tag or commit SHA)

jobs:
  # Build an app package from the given source code reference.
  build:
    name: Build app package
    uses: ./.github/workflows/5_builderprecompiled_base-dev-environment.yml
    with:
      reference: ${{ inputs.reference }}
      command: 'yarn build'
      artifact_name: 'wazuh-security-dashboards-plugin'
      artifact_path: './wazuh-security-plugin/build'
    secrets: inherit
